# architecture
arch: vit_base
enc_arch: SimCLRViTEncoder
dec_arch: SimCLRViTDecoder

# wandb
proj_name: simclr3d
run_name: ${proj_name}_${arch}_${dataset}
wandb_id:
disable_wandb: True

# dataset
dataset: lung
json_list: 'train.json'
data_path: ''

# output
output_dir: ''
ckpt_dir: ${output_dir}/ckpts

# data preprocessing
space_x: 1
space_y: 1
space_z: 1
a_min: -1024.0
a_max: 3071.0
b_min: 0.0
b_max: 1.0
roi_x: 48
roi_y: 48
roi_z: 48
RandFlipd_prob: 0.2
RandRotate90d_prob: 0.2
RandScaleIntensityd_prob: 0.1
RandShiftIntensityd_prob: 0.1

# trainer
trainer_name: SimCLR3DTrainer
batch_size: 64
vis_batch_size: 1
start_epoch: 0
warmup_epochs: 40
epochs: 1000
workers: 4
resume:

# model
patchembed: 'PatchEmbed3D'
pos_embed_type: 'sincos'
mask_ratio: 0.75
input_size: ${roi_x}
patch_size: 8
in_chans: 1
encoder_embed_dim: 768
encoder_depth: 12
encoder_num_heads: 12
decoder_embed_dim: 384
decoder_depth: 8
decoder_num_heads: 12
patch_dim: 512
feature_size: 16
spatial_dims: 3
out_channels: 1
temperature: 0.5

#SimCLR:
mlp_dim : 4096
output_dim : 256

# optimizer
type: adamw
lr:
beta1: 0.9
beta2: 0.95
weight_decay: .1

# logging
vis_freq: 100
save_freq: 1000
print_freq: 1

# distributed processing
gpu: 0
dist_url:
world_size: 1
multiprocessing_distributed: True
dist_backend: nccl
distributed:
rank: 0
ngpus_per_node: 4
num_samples: 1

# randomness
seed:

# debugging
debug: false
